version: "3"

services:
  elasticsearch7.17:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    container_name: es7.17
    profiles: ["es7", "all"]
    environment:
      - cluster.name=elastomer7.17
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esrepos7:/usr/share/elasticsearch/repos
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 127.0.0.1:${ES_7_PORT:-9207}:9200
  
  elasticsearch5.6:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    container_name: es5.6
    profiles: ["es5", "all"]
    environment:
      - cluster.name=elastomer5.6
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esrepos5:/usr/share/elasticsearch/repos
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 127.0.0.1:${ES_5_PORT:-9205}:9200

  elasticsearch2.4:
    image: elasticsearch:2.4.6
    container_name: es2.4
    profiles: ["es2"] # Leave off "all" since ES 2 will be going away soon
    environment:
      - cluster.name=elastomer2.4
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esrepos2:/usr/share/elasticsearch/repos
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 127.0.0.1:${ES_2_PORT:-9202}:9200

volumes:
  esrepos7:
    driver: local
    driver_opts:
      device: tmpfs
      type: tmpfs
      o: size=100m,uid=102,gid=102
  esrepos5:
    driver: local
    driver_opts:
      device: tmpfs
      type: tmpfs
      o: size=100m,uid=102,gid=102
  esrepos2:
    driver: local
    driver_opts:
      device: tmpfs
      type: tmpfs
      o: size=100m,uid=102,gid=102
