version: "2.1"

services:
  elasticsearch2.4:
    image: elasticsearch:2.4.6
    container_name: es2.4
    environment:
      - cluster.name=elastomer2.4
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esrepos:/usr/share/elasticsearch/repos
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 127.0.0.1:9200:9200

volumes:
  esrepos:
    driver: local
    driver_opts:
      device: tmpfs
      type: tmpfs
      o: size=100m,uid=102,gid=102
